export const CATEGORY_TEMPLATES: Record<string, string[]> = {
  "mini-supermarket": [
    "Food & Beverages",
    "Household & Cleaning",
    "Personal Care",
    "Baby Products",
    "Snacks & Confectionery",
    "Cooking Oil & Fats",
    "Dairy",
    "Bread & Bakery",
    "Stationery",
    "Alcoholic Beverages",
    "Soft Drinks",
    "Cereals & Grains",
    "Canned & Packaged Foods",
    "Frozen Foods",
    "Other",
  ],
  hardware: [
    "Electrical",
    "Plumbing",
    "Paint & Finishes",
    "Tools",
    "Fasteners",
    "Building Materials",
    "Timber",
    "Safety & PPE",
    "Adhesives & Sealants",
    "Locks & Security",
    "Other",
  ],
  cosmetics: [
    "Hair Care",
    "Skin Care",
    "Makeup",
    "Nails",
    "Fragrances",
    "Wigs & Extensions",
    "Accessories",
    "Body Care",
    "Men's Grooming",
    "Other",
  ],
  pharmacy: [
    "Prescription",
    "OTC Pain & Fever",
    "Cold & Flu",
    "Digestive",
    "Vitamins & Supplements",
    "First Aid",
    "Personal Care",
    "Baby & Maternal",
    "Skin & Derma",
    "Other",
  ],
  "wines-spirits": [
    "Spirits",
    "Beer",
    "Wine",
    "Soft Drinks & Mixers",
    "Cigarettes",
    "Snacks",
    "Other",
  ],
  "phone-electronics": [
    "Phone Cases & Covers",
    "Chargers & Cables",
    "Earphones & Audio",
    "Screen Protectors",
    "Power Banks",
    "Memory Cards & Storage",
    "Phone Accessories",
    "Small Electronics",
    "Repairs & Parts",
    "Other",
  ],
  "auto-spare-parts": [
    "Engine Parts",
    "Brakes & Suspension",
    "Filters",
    "Electrical & Lighting",
    "Body Parts",
    "Oils & Fluids",
    "Belts & Hoses",
    "Tyres & Wheels",
    "Accessories",
    "Other",
  ],
  "agro-vet": [
    "Seeds",
    "Fertilizers",
    "Pesticides & Herbicides",
    "Animal Feeds",
    "Veterinary Drugs",
    "Farm Tools",
    "Irrigation & Water",
    "Poultry Supplies",
    "Dairy Supplies",
    "Other",
  ],
  clothing: [
    "Men's Clothing",
    "Women's Clothing",
    "Children's Clothing",
    "Shoes & Footwear",
    "Bags & Accessories",
    "Undergarments",
    "Sportswear",
    "Other",
  ],
  stationery: [
    "Writing Instruments",
    "Notebooks & Paper",
    "Art & Craft",
    "School Supplies",
    "Office Supplies",
    "Printing & Ink",
    "Filing & Storage",
    "Other",
  ],
  general: [
    "General",
    "Other",
  ],
};

export const BUSINESS_TYPES = Object.keys(CATEGORY_TEMPLATES);
